"""add checkout table

Revision ID: 4118f0fe3774
Revises: bd0287ba674a
Create Date: 2025-11-15 00:22:57.353035

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '4118f0fe3774'
down_revision = 'bd0287ba674a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkouts',
    sa.Column('checkout_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('checkout_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkouts')
    # ### end Alembic commands ###
